### ISSUE TITLE
Ivan's Mod suggestions

### ISSUE THREAD

**Issue by fruitmeister101** [lmao5677/lmao5677.github.io#1]
I'm going to preface this by saying, I don't know your schedule or personal life or current situations or anything, but please consider the following.

Ivan's Mod does not have a real wiki, but waaaay back in the day when I first downloaded it, it came with a wiki-like text file, describing and clarifying the weapons/enemies/compo items and such. If it is not too much trouble, I would ask that - if it is available to you - you provide the "Wiki". =D
Also, Ivan's Mod Seaside A can't load the boss level.

Thank you for your time, and thank you for providing this great mod of an amazing game! =D (Don't lose us our access to it, and I would love if Ivan or haii55 support you guys)
Good luck ;D

**Comment by lmao5677** [comment]
Sorry, but I don't have any SR nodding files on me anymore. Also upon the owners request I have deleted the mod from the site, because I never received permission originally. I can't really remember why I uploaded it in the first place, but I don't want to carry a responsibility of handling a community for it. There is also no way either Ivan or ha55i would even consider supporting as I've already told you about how Ivan feels about it, and iirc ha55i is basically Nintendo. If anything he would try his best to take it down.

**Comment by fruitmeister101** [comment]
It's so sad that the original was abused. I have always loved stick ranger,
but Ivan did such a good job with the mod, it made me love it even more.
I understand, am grateful for a chance to enjoy it again for a while, and
wish you the best of luck.
-Samuel Herron-
